//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkladBDEntities : DbContext
    {
        public SkladBDEntities()
            : base("name=SkladBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classification> classification { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
